config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages do
      collection do
        get 'category'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'カテゴリーを選択' },
    { id: 2, name: 'ごはん' },
    { id: 3, name: 'トイレ' },
    { id: 4, name: '体重' },
    { id: 5, name: '写真' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many_attached :images
  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    images.attached?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  validates :category_id, numericality: { other_than: 1 }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])

    @messages = if params[:category_id].present? && params[:category_id] != ''
                  @room.messages.where(category_id: params[:category_id]).includes(:user)
                else
                  @room.messages.includes(:user)
                end
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index, status: :unprocessable_entity
    end

    respond_to do |format|
      format.html # 通常のHTMLレスポンス
      format.json { render json: @messages } # JSONレスポンス
    end
  end

  # カテゴリ検索用アクション
  def category
    category_id = params[:category_id]
    # カテゴリに基づいてメッセージをフィルタリング
    if category_id.present?
      messages = Message.where(category_id: category_id)
    else
      messages = Message.all
    end
    # JSON形式でメッセージを返す
    render json: { messages: render_to_string(partial: 'messages/message', collection: messages) }
  end

  private

  def message_params
    params.require(:message).permit(:content, :category_id, images: []).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    user_ids = params[:room][:user_ids].split(',').map(&:to_i) # 文字列から整数に変換
    selected_users = User.where(id: user_ids).to_a

    # current_user を選択されたユーザーに追加
    selected_users << current_user

    if @room.save
      # 選択されたユーザーをチャットルームのメンバーに追加
      @room.users = selected_users # ここで users リレーションを上書き

      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>にゃんログ</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class= "main">
  <div class="chat-header">
    <div class="left-header">
      <div class="back-button">
        <button id="back-button">
          <i class="fa-solid fa-angle-left"></i>
        </button>
      </div>
      <div class="header-title">
        <%= @room.name %>
      </div>
      <div class="header-category">
        <%= form_tag(category_room_messages_path(@room), method: :get, class: 'category-filter', remote: true) do %>
          <%= select_tag :category_id, options_for_select([['全て', ''], *Category.where(id: 2..6).pluck(:name, :id)], (params[:category_id] || '')), class: 'filter-selectbox', id: 'category-select' %>
        <% end %>
      </div>
    </div>
    <div class="right-header">
      <div class="header-button">
        <%= link_to "チャットを終了する", room_path(@room), data: { turbo_method: :delete } %>
      </div>
    </div>
  </div>

  <div class="messages" id="chat-messages">
    <%= render partial: 'message', collection: @messages %>
  </div>

  <%= form_with model: [@room, @message], data: {turbo: false}, class: 'form', local: true do |f| %>
    <div class="form-input">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"message-category"}) %>
      <div class="content-form">
        <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
        <label class="form-image">
          <span class="image-icon">
            <i class="fas fa-paperclip"></i>
          </span>
          <%= f.file_field :images, multiple: true, accept: "image/*" , class: 'hidden' %>
        </label>
      </div>
    </div>
    <%= button_tag type: "submit", class: 'form-submit', id: 'form-btn' do%>
      <i class="fa-solid fa-location-arrow"></i>
    <% end %>
  <% end %>
</div>

<script>
  // ページ読み込み時と新しいメッセージ追加時に最下部にスクロール
  document.addEventListener("turbo:load", function() {
    const chatMessages = document.getElementById('chat-messages');
    chatMessages.scrollTop = chatMessages.scrollHeight;
  });

  // カテゴリー選択が変更されたときに非同期リクエストを送信
  $('#category-select').change(function () {
    const selectedCategoryId = $(this).val();
    $.ajax({
      url: '<%= category_room_messages_path(@room) %>',
      method: 'GET',
      data: { category_id: selectedCategoryId },
      dataType: 'json',
      success: function (response) {
        // レスポンスを使ってページを更新
        // 例えば、メッセージリストを再描画するなど
        const chatMessages = document.getElementById('chat-messages');
        chatMessages.innerHTML = response.messages; // メッセージリストを更新
      },
      error: function (error) {
        console.error('Error:', error);
      }
    });
  });

  // 画像選択時の制限
  document.addEventListener("DOMContentLoaded", function() {
    document.querySelector('.hidden').addEventListener('change', function(e) {
      if (e.target.files.length > 8) {
        alert("最大8枚までしか選択できません。");
        e.target.value = ''; // 選択をクリアする
      }
    });
  });
</script>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <% message.images.each do |image| %>
      <%= image_tag image.variant(resize: '500x500'), class: 'message-image' if message.images.attached? %>
    <% end %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side">
  <div class="side-bar-header">
      <div class="header-name">
        <%= link_to current_user.name, edit_user_path(current_user) %>      
      </div>
    <div class="create-room">
      <%= link_to "チャットを作成する", new_room_path, data: {turbo: false} %>
    </div>
  </div>
  <div class="rooms">
    <% current_user.rooms.each do |room| %>
      <div class="room">
        <div class="room-name">
          <%= link_to room.name, room_messages_path(room), data: {turbo: false} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<body>
  <div class="wrapper">
    <div class="side-bar" id="side-bar">
      <%= render "side_bar"%>
    </div>
    <div class="chat">
      <%= render "main_chat" %>
    </div>
  </div>

<script>
// ページが読み込まれたときに実行されるJavaScript
document.addEventListener('DOMContentLoaded', function () {
  const backButton = document.getElementById('back-button');
  const sideBar = document.getElementById('side-bar');

  // ＜ボタンがクリックされたときの処理
  backButton.addEventListener('click', () => {
    // side-bar の表示状態を切り替える
    if (sideBar.style.display === 'none' || sideBar.style.display === '') {
      sideBar.style.display = 'block';
    } else {
      sideBar.style.display = 'none';
    }
  });

  // スマホサイズでのみ side-bar をデフォルトで非表示にする
  const isMobile = window.innerWidth <= 980;
  if (isMobile) {
    sideBar.style.display = 'none';
  };
});
</script>
</body>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%= form_with model: @room, data: {turbo: false}, local: true do |f| %>
    <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label' %>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください' %>
      </div>
    </div>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='room_user_ids'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <div class="user-seach-form">
          <input type="text" class="user-seach" id="user-search" placeholder="ユーザーを検索">
          <select name='room[user_ids][]' id='room_user_ids' class='user-select' multiple='multiple'>
            <% User.where.not(id: current_user.id).each do |user| %>
              <option value='<%= user.id %>'><%= user.name %></option>
            <% end %>
          </select>
        </div>
        <div class="add-user-button">
          <button type="button" id="add-user-button">追加</button>
        </div>
        <div class='user-list' id='selected-users-list'>
            <div id="selected-users"></div>
        </div>
      </div>
    </div>

    <!-- 削除ボタンがクリックされたときに選択したユーザーIDを保持するためのフィールド -->
    <%= f.hidden_field :user_ids, id: 'selected-user-ids' %>
    
    <div class='chat-room-form__field'>
      <%= f.submit '新しいチャットルームを作成', class: 'chat-room-form__action-btn' %>
    </div>
  <% end %>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
  // ユーザー追加ボタンのクリックイベント
  const addUserButton = document.getElementById('add-user-button');
  const selectedUsers = document.getElementById('selected-users');
  const userSelect = document.getElementById('room_user_ids'); // userSelect を追加

  // ユーザーIDを保持する隠しフィールド
  const selectedUserIdsInput = document.getElementById('selected-user-ids');
  const selectedUserIds = [];

  addUserButton.addEventListener('click', function () {
    const selectedUserId = userSelect.value;
    const selectedUserName = userSelect.options[userSelect.selectedIndex].text;

    // 選択したユーザーを表示するための要素を作成
    const userElement = document.createElement('div');
    userElement.textContent = selectedUserName;
    userElement.classList.add('add-user-name');

    // 選択したユーザーを一時的に保持する要素に追加
    selectedUsers.appendChild(userElement);

    // 削除ボタンを作成
    const removeUserButton = document.createElement('button');
    removeUserButton.type = 'button';
    removeUserButton.classList.add('remove-user-button');
    removeUserButton.textContent = '×';

    // 削除ボタンをユーザーエレメントに追加
    userElement.appendChild(removeUserButton);

    // 削除ボタンのクリックイベント
    removeUserButton.addEventListener('click', function () {
      // ユーザーエレメントを削除
      userElement.remove();
      
      // ユーザーIDをselectedUserIdsから削除
      const index = selectedUserIds.indexOf(selectedUserId);
      if (index > -1) {
        selectedUserIds.splice(index, 1);
      }
      
      // selectedUserIdsをカンマ区切りの文字列に変換
      selectedUserIdsInput.value = selectedUserIds.join(',');
    });
    
    // ユーザーIDをselectedUserIdsに追加
    selectedUserIds.push(selectedUserId);
    
    // selectedUserIdsをカンマ区切りの文字列に変換
    selectedUserIdsInput.value = selectedUserIds.join(',');
    
    // 選択したユーザーを再選択可能にする
    userSelect.options[userSelect.selectedIndex].disabled = false;
  });
});

// ユーザー検索
document.addEventListener('DOMContentLoaded', function () {
  const userSearchInput = document.getElementById('user-search');
  const userSelect = document.getElementById('room_user_ids'); // 既存のセレクトボックス

  // セレクトボックスを初期非表示にする
  userSelect.style.display = 'none';

  userSearchInput.addEventListener('input', function () {
    const searchValue = userSearchInput.value.toLowerCase(); // 入力値を小文字に変換

    // セレクトボックス内の全てのオプションを取得
    const options = userSelect.querySelectorAll('option');

    if (searchValue) {
      // 検索テキストボックスに何か入力された場合、セレクトボックスを表示
      userSelect.style.display = 'block';

      options.forEach(function (option) {
        const userName = option.textContent.toLowerCase();

        // ユーザー名が検索文字列を含む場合は表示、それ以外は非表示にする
        if (userName.includes(searchValue)) {
          option.style.display = 'block'; // 表示
        } else {
          option.style.display = 'none'; // 非表示
        }
      });
    } else {
      // 検索テキストボックスが空の場合、セレクトボックスを非表示
      userSelect.style.display = 'none';
    }
  });
});
</script>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>